export const SDGS = [
  { id: 1, title: "No Poverty", color: "#E5243B", icon: "/sdgs/1.jpg" },
  { id: 2, title: "Zero Hunger", color: "#DDA63A", icon: "/sdgs/2.jpg" },
  { id: 3, title: "Good Health & Well-being", color: "#4C9F38", icon: "/sdgs/3.jpg" },
  { id: 4, title: "Quality Education", color: "#C5192D", icon: "/sdgs/4.jpg" },
  { id: 5, title: "Gender Equality", color: "#FF3A21", icon: "/sdgs/5.jpg" },
  { id: 6, title: "Clean Water & Sanitation", color: "#26BDE2", icon: "/sdgs/6.jpg" },
  { id: 7, title: "Affordable & Clean Energy", color: "#FCC30B", icon: "/sdgs/7.jpg" },
  { id: 8, title: "Decent Work & Economic Growth", color: "#A21942", icon: "/sdgs/8.jpg" },
  { id: 9, title: "Industry, Innovation & Infrastructure", color: "#FD6925", icon: "/sdgs/9.jpg" },
  { id: 10, title: "Reduced Inequalities", color: "#DD1367", icon: "/sdgs/10.jpg" },
  { id: 11, title: "Sustainable Cities & Communities", color: "#FD9D24", icon: "/sdgs/11.jpg" },
  { id: 12, title: "Responsible Consumption & Production", color: "#BF8B2E", icon: "/sdgs/12.jpg" },
  { id: 13, title: "Climate Action", color: "#3F7E44", icon: "/sdgs/13.jpg" },
  { id: 14, title: "Life Below Water", color: "#0A97D9", icon: "/sdgs/14.jpg" },
  { id: 15, title: "Life on Land", color: "#56C02B", icon: "/sdgs/15.jpg" },
  { id: 16, title: "Peace, Justice & Institutions", color: "#00689D", icon: "/sdgs/16.jpg" },
  { id: 17, title: "Partnerships for the Goals", color: "#19486A", icon: "/sdgs/17.jpg" },
]
