export const SEED_STUDENTS = [
  {
    id: "stu-101",
    name: "Aarav Sharma",
    college: "IIT Indore",
    skills: ["React", "Node.js", "UI/UX"],
    experience: 6,
    profileScore: 92,
    appliedInternships: [],
    progress: {},
  },
  {
    id: "stu-102",
    name: "Ishika Verma",
    college: "DAVV",
    skills: ["Content Writing", "Social Media", "Communication"],
    experience: 3,
    profileScore: 88,
    appliedInternships: [],
    progress: {},
  },
  {
    id: "stu-103",
    name: "Rohan Gupta",
    college: "Acropolis Institute",
    skills: ["Python", "ML", "Data Cleaning"],
    experience: 12,
    profileScore: 95,
    appliedInternships: [],
    progress: {},
  },
  {
    id: "stu-104",
    name: "Priya Mehta",
    college: "Medicaps University",
    skills: ["Event Management", "Leadership"],
    experience: 4,
    profileScore: 85,
    appliedInternships: [],
    progress: {},
  },
  {
    id: "stu-105",
    name: "Harshit Raj",
    college: "SGSITS",
    skills: ["Video Editing", "Canva", "PR"],
    experience: 8,
    profileScore: 90,
    appliedInternships: [],
    progress: {},
  },
];
